/aruco_car_node:
  ros__parameters:
    marker_size: 0.02
    aruco_dictionary_id: DICT_4X4_50
    image_topic: /oak/rgb/image_raw
    camera_info_topic: /oak/rgb/camera_info
    camera_frame: oak_rgb_camera_optical_frame

/aruco_city_node:
  ros__parameters:
    marker_size: 0.02
    aruco_dictionary_id: DICT_5X5_50
    image_topic: /oak/rgb/image_raw
    camera_info_topic: /oak/rgb/camera_info
    camera_frame: oak_rgb_camera_optical_frame
