teleop_twist_joy_node:
  ros__parameters:
    axis_linear: # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 0.5

    axis_angular: # Left thumb stick horizontal
      yaw: 0
    scale_angular:
      yaw: 7.7

    enable_button: 2 # Left trigger button
    enable_turbo_button: 5 # Right trigger button
