twist_mux_node:
  ros__parameters:
    topics:
      joystick:
        topic: joy_vel
        timeout: 0.5
        priority: 10
      drive:
        topic: drive_vel
        timeout: 0.5
        priority: 20 
