twist_mux_node:
  ros__parameters:
    topics:
      null:
        topic: cmd_null
        timeout: 0.5
        priority: 1
      drive:
        topic: cmd_drive
        timeout: 0.5
        priority: 10
      joystick:
        topic: cmd_joy
        timeout: 0.5
        priority: 20
      car_detection:
        topic: cmd_detected_car
        timeout: 0.5
        priority: 255
